### ISSUE TITLE
Hello There , Prathamesh here 

### ISSUE THREAD

**Issue by PrathameshBhagat** [mindsers/nathanael-dev#1]
I actually I don't have an issue in your project/repo , I am a third year B.Tech(C.S)  living in India (Nagpur, Maharashtra )  student may I know  which company do you work in ? As I am a student and I am in search of some  guidance . Can I get your phone number , please ???

**Comment by mindsers** [comment]
Hi,
Github projects' issues aren't a messaging app. I'm present on many social media. It is possible to reach out to me there if you want.
